### PR TITLE
Oilylime/hyperdrive support

### PR DESCRIPTION
**Pull request by mtlemilio**

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
Hey great PR, was curious if you were planning on adding tests?

**Comment by mtlemilio** [comment]
> Hey great PR, was curious if you were planning on adding tests?

Will do.

**Comment by mtlemilio** [comment]
@JacobMGEvans rebased and added tests and changeset, will also move this PR to point at the upstream

**Comment by mtlemilio** [comment]
https://github.com/cloudflare/workers-sdk/pull/3999

**Pull request closed without merging**
